### ISSUE TITLE
Use a custom package not the automata namespace

### ISSUE THREAD

**Issue by duergner** [zalando-incubator/aws-support-spring-boot-starter#2]
As this starter is no longer part of automata-misc it should use a distinct customer package to reflect that.

Proposal would be `org.zalando.spring.boot.starter.awssupport`

**Comment by duergner** [comment]
@jbellmann / @LappleApple any objections / comments from your side?

**Comment by jbellmann** [comment]
Can we skip 'support' from the last package-name?

**Comment by duergner** [comment]
Fine with me
